/**
 * Auction locations and their transport prices.
 *
 * Extracted verbatim from the original hard-coded table in
 * list.component.ts; this file is the seed source for the `states` table and
 * is not read at runtime. After seeding, prices are edited in the database.
 */
export const STATES_SEED: ReadonlyArray<{ name: string; price: number }> = [
  { name: "AL-MOBILE", price: 2085 },
  { name: "AL-MOBILE SOUTH", price: 2075 },
  { name: "AL-MONTGOMERY", price: 2100 },
  { name: "AL-TANNER", price: 2100 },
  { name: "AR-FAYETTEVILLE", price: 2390 },
  { name: "AR-LITTLE ROCK", price: 2360 },
  { name: "AZ-PHOENIX", price: 2835 },
  { name: "AZ-PHOENIX NORTH", price: 2715 },
  { name: "AZ-TUCSON", price: 2775 },
  { name: "CA STOCKTON (IAAI) ", price: 2825 },
  { name: "CA-ADELANTO", price: 2535 },
  { name: "CA-ANTELOPE", price: 2750 },
  { name: "CA-BAKERSFIELD", price: 2600 },
  { name: "CA-CRASHEDTOYS SACRAMENTO", price: 2805 },
  { name: "CA-FRESNO", price: 2675 },
  { name: "CA-HAYWARD", price: 2725 },
  { name: "CA-HAYWARD - DESERT VIEW", price: 2885 },
  { name: "CA-LONG BEACH", price: 2525 },
  { name: "CA-LOS ANGELES", price: 2575 },
  { name: "CA-MARTINEZ", price: 2700 },
  { name: "CA-MENTONE", price: 2575 },
  { name: "CA-NAPA", price: 2805 },
  { name: "CA-RANCHO CUCAMONGA", price: 2585 },
  { name: "CA-REDDING", price: 3865 },
  { name: "CA-SACRAMENTO", price: 2725 },
  { name: "CA-SAN BERNARDINO", price: 2545 },
  { name: "CA-SAN DIEGO", price: 2665 },
  { name: "CA-SAN JOSE", price: 2700 },
  { name: "CA-SO SACRAMENTO", price: 2725 },
  { name: "CA-SUN VALLEY", price: 2525 },
  { name: "CA-VALLEJO", price: 2700 },
  { name: "CA-VAN NUYS", price: 2575 },
  { name: "CO-COLORADO SPRINGS", price: 2565 },
  { name: "CO-DENVER", price: 2575 },
  { name: "CO-DENVER CENTRAL", price: 2575 },
  { name: "CO-DENVER SOUTH", price: 2575 },
  { name: "CT-HARTFORD", price: 1975 },
  { name: "CT-HARTFORD SPRINGFIELD", price: 2050 },
  { name: "FL-CLEWISTON", price: 2255 },
  { name: "FL-FT. PIERCE", price: 2075 },
  { name: "FL-JACKSONVILLE EAST", price: 1925 },
  { name: "FL-JACKSONVILLE NORTH", price: 1925 },
  { name: "FL-JACKSONVILLE WEST", price: 1925 },
  { name: "FL-MIAMI CENTRAL", price: 2075 },
  { name: "FL-MIAMI NORTH", price: 2075 },
  { name: "FL-MIAMI SOUTH", price: 2075 },
  { name: "FL-OCALA", price: 2075 },
  { name: "FL-ORLANDO", price: 2075 },
  { name: "FL-ORLANDO NORTH", price: 2075 },
  { name: "FL-ORLANDO SOUTH", price: 2075 },
  { name: "FL-PUNTA GORDA", price: 2225 },
  { name: "FL-TALLAHASSEE", price: 2275 },
  { name: "FL-TAMPA SOUTH", price: 2075 },
  { name: "FL-WEST PALM BEACH", price: 2075 },
  { name: "GA - AUGUSTA", price: 2025 },
  { name: "GA-ATLANTA EAST", price: 2025 },
  { name: "GA-ATLANTA NORTH", price: 1975 },
  { name: "GA-ATLANTA SOUTH", price: 2165 },
  { name: "GA-ATLANTA WEST", price: 2025 },
  { name: "GA-CARTERSVILLE", price: 2025 },
  { name: "GA-FAIRBURN", price: 2115 },
  { name: "GA-MACON", price: 2115 },
  { name: "GA-SAVANNAH", price: 1965 },
  { name: "GA-TIFTON", price: 2045 },
  { name: "IA-CEDAR RAPIDS", price: 2325 },
  { name: "IA-DAVENPORT", price: 2325 },
  { name: "IA-DES MOINES", price: 2325 },
  { name: "ID-BOISE", price: 3075 },
  { name: "IL-CHICAGO NORTH", price: 2225 },
  { name: "IL-CHICAGO SOUTH", price: 2225 },
  { name: "IL-PEORIA", price: 2255 },
  { name: "IL-SOUTHERN ILLINOIS", price: 2275 },
  { name: "IL-WHEELING", price: 2225 },
  { name: "IN-CICERO", price: 2325 },
  { name: "IN-DYER", price: 2275 },
  { name: "IN-FORT WAYNE", price: 2225 },
  { name: "IN-INDIANAPOLIS", price: 2250 },
  { name: "KS-KANSAS CITY", price: 2475 },
  { name: "KS-WICHITA", price: 2445 },
  { name: "KY-EARLINGTON", price: 2415 },
  { name: "KY-LEXINGTON EAST", price: 2375 },
  { name: "KY-LEXINGTON WEST", price: 2275 },
  { name: "KY-LOUISVILLE", price: 2415 },
  { name: "KY-WALTON", price: 2375 },
  { name: "LA-BATON ROUGE", price: 2325 },
  { name: "LA-NEW ORLEANS", price: 2265 },
  { name: "LA-SHREVEPORT", price: 2265 },
  { name: "MA-FREETOWN", price: 2265 },
  { name: "MA-NORTH BOSTON", price: 2025 },
  { name: "MA-SOUTH BOSTON", price: 2025 },
  { name: "MA-WEST WARREN", price: 2025 },
  { name: "MD- ELKTON (IAAI) ", price: 2075 },
  { name: "MD-BALTIMORE", price: 2000 },
  { name: "MD-BALTIMORE EAST", price: 2050 },
  { name: "MD-LAUREL (SUBLOT შეამოწმეთ) ", price: 2125 },
  { name: "ME - WINDHAM", price: 2325 },
  { name: "ME-GRAY (SUBLOT შეამოწმეთ)", price: 2175 },
  { name: "ME-LYMAN", price: 2175 },
  { name: "ME-ORONO (SUBLOT შეამოწმეთ)", price: 2340 },
  { name: "MI- WAYLAND", price: 2375 },
  { name: "MI-DETROIT", price: 2275 },
  { name: "MI-FLINT", price: 2460 },
  { name: "MI-IONIA", price: 2325 },
  { name: "MI-KINCHELOE", price: 2645 },
  { name: "MI-LANSING", price: 2275 },
  { name: "MN-BIG LAKE (SUBLOT შეამოწმეთ)", price: 2375 },
  { name: "MN-CRASHEDTOYS EAST BETHEL", price: 2410 },
  { name: "MN-MINNEAPOLIS", price: 2315 },
  { name: "MN-ST. CLOUD", price: 2315 },
  { name: "MO-COLUMBIA", price: 2275 },
  { name: "MO-SIKESTON", price: 2275 },
  { name: "MO-SPRINGFIELD", price: 2325 },
  { name: "MO-ST.LOUIS", price: 2325 },
  { name: "MS-GRENADA", price: 2395 },
  { name: "MS-JACKSON", price: 2305 },
  { name: "MT-HELENA", price: 3375 },
  { name: "NC-CHINA GROVE", price: 2270 },
  { name: "NC-CONCORD", price: 1975 },
  { name: "NC-GASTONIA", price: 2175 },
  { name: "NC-LUMBERTON", price: 2125 },
  { name: "NC-MEBANE", price: 2035 },
  { name: "NC-MOCKSVILLE", price: 2005 },
  { name: "NC-RALEIGH", price: 2105 },
  { name: "NC-RALEIGH NORTH", price: 2125 },
  { name: "ND-BISMARCK", price: 2875 },
  { name: "NE-LINCOLN", price: 2400 },
  { name: "NH-CANDIA", price: 2125 },
  { name: "NJ SAYREVILLE (IAAI)", price: 1875 },
  { name: "NJ- PORT MURRAY (IAAI)", price: 1905 },
  { name: "NJ-GLASSBORO EAST", price: 1950 },
  { name: "NJ-GLASSBORO WEST", price: 1950 },
  { name: "NJ-SOMERVILLE", price: 1885 },
  { name: "NJ-TRENTON", price: 1885 },
  { name: "NM-ALBUQUERQUE", price: 2675 },
  { name: "NV-LAS VEGAS", price: 2695 },
  { name: "NV-LAS VEGAS WEST", price: 2775 },
  { name: "NV-RENO", price: 2875 },
  { name: "NY-ALBANY", price: 2015 },
  { name: "NY-BUFFALO", price: 2195 },
  { name: "NY-LONG ISLAND", price: 1985 },
  { name: "NY-NEWBURGH", price: 1985 },
  { name: "NY-ROCHESTER", price: 2115 },
  { name: "NY-SYRACUSE", price: 2035 },
  { name: "OH-AKRON", price: 2125 },
  { name: "OH-CLEVELAND EAST", price: 2175 },
  { name: "OH-CLEVELAND WEST", price: 2175 },
  { name: "OH-COLUMBUS", price: 2175 },
  { name: "OH-DAYTON", price: 2175 },
  { name: "OK-OKLAHOMA CITY", price: 2325 },
  { name: "OK-TULSA", price: 2325 },
  { name: "OR-EUGENE", price: 3000 },
  { name: "OR-PORTLAND NORTH", price: 3000 },
  { name: "OR-PORTLAND SOUTH", price: 3000 },
  { name: "PA-ALTOONA", price: 2215 },
  { name: "PA-CHAMBERSBURG", price: 2135 },
  { name: "PA-HARRISBURG", price: 2065 },
  { name: "PA-PHILADELPHIA EAST", price: 1955 },
  { name: "PA-PHILADEPHIA", price: 1955 },
  { name: "PA-PITTSBURGH NORTH", price: 2135 },
  { name: "PA-PITTSBURGH SOUTH", price: 2135 },
  { name: "PA-PITTSBURGH WEST", price: 2135 },
  { name: "PA-SCRANTON", price: 1985 },
  { name: "PA-YORK HAVEN", price: 2065 },
  { name: "RI-EXETER", price: 2050 },
  { name: "SC-COLUMBIA!!!!", price: 2165 },
  { name: "SC-NORTH CHARLESTON", price: 1935 },
  { name: "SC-SOUTH GASTON !!!!(SUBLOT შეამოწმეთ)", price: 1990 },
  { name: "SC-SPARTANBURG!!!!!!", price: 2175 },
  { name: "TN-KNOXVILLE", price: 2275 },
  { name: "TN-MEMPHIS!!!!", price: 2315 },
  { name: "TN-NASHVILLE!!!!", price: 2315 },
  { name: "TX-ABILENE", price: 2275 },
  { name: "TX-AMARILLO", price: 2425 },
  { name: "TX-ANDREWS", price: 2400 },
  { name: "TX-AUSTIN", price: 2175 },
  { name: "TX-CORPUS CHRISTI", price: 2185 },
  { name: "TX-CRASHEDTOYS DALLAS", price: 2145 },
  { name: "TX-DALLAS", price: 2175 },
  { name: "TX-DALLAS SOUTH", price: 2175 },
  { name: "TX-EL PASO!!!!!!!!", price: 2400 },
  { name: "TX-FT.WORTH", price: 2215 },
  { name: "TX-HOUSTON!!!", price: 2085 },
  { name: "TX-HOUSTON EAST!!!!", price: 2075 },
  { name: "TX-LONGVIEW", price: 2185 },
  { name: "TX-MCALLEN!!!!", price: 2245 },
  { name: "TX-NORTH AUSTIN!!!!", price: 2275 },
  { name: "TX-SAN ANTONIO", price: 2265 },
  { name: "TX-WACO", price: 2185 },
  { name: "UT-OGDEN", price: 2085 },
  { name: "UT-SALT LAKE CITY", price: 2885 },
  { name: "VA-DANVILLE", price: 2175 },
  { name: "VA-FREDERICKSBURG", price: 2125 },
  { name: "VA-HAMPTON", price: 2125 },
  { name: "VA-RICHMOND", price: 2075 },
  { name: "VA-RICHMOND EAST", price: 2125 },
  { name: "WA-GRAHAM", price: 2800 },
  { name: "WA-NORTH SEATTLE", price: 2925 },
  { name: "WA-PASCO", price: 2925 },
  { name: "WA-SPOKANE", price: 3025 },
  { name: "AK-ANCHORAGE", price: 5850 },
  { name: "AL-BIRMINGHAM", price: 2100 },
  { name: "AL-DOTHAN", price: 2065 },
  { name: "AL-HUNTSVILLE (IAAI)", price: 2085 },
  { name: "AR-FAYETTEVILLE (IAAI)", price: 2390 },
  { name: "AR-LITTLE ROCK (IAAI)", price: 2360 },
  { name: "AZ-PHOENIX (IAAI)", price: 2835 },
  { name: "AZ-TUCSON (IAAI)", price: 2925 },
  { name: "CA-ACE CARSON (ACE)", price: 2605 },
  { name: "CA-ACE PERRIS (ACE)", price: 2605 },
  { name: "CA-ANAHEIM (IAAI)", price: 2535 },
  { name: "CA-COLTON (IAAI)", price: 2580 },
  { name: "CA-EAST BAY (IAAI)", price: 2875 },
  { name: "CA-FONTANA (IAAI)", price: 2605 },
  { name: "CA-FREMONT (IAAI)", price: 2875 },
  { name: "CA-FRESNO (IAAI)", price: 2725 },
  { name: "CA-HIGH DESERT (IAAI)", price: 2645 },
  { name: "CA-IAA RIVERSIDE (IAAI)", price: 2685 },
  { name: "CA-LOS ANGELES (IAAI)", price: 2645 },
  { name: "CA-NORTH HOLLYWOOD (IAAI)", price: 2535 },
  { name: "CA-RIVERSIDE (IAAI)", price: 2565 },
  { name: "CA-SACRAMENTO (IAAI)", price: 2805 },
  { name: "CA-SAN DIEGO (IAAI)", price: 2605 },
  { name: "CA-SANTA CLARITA (IAAI)", price: 2635 },
  { name: "CA-STOCKTON (IAAI)", price: 2950 },
  { name: "CO-COLORADO SPRINGS (IAAI)", price: 2750 },
  { name: "CO-DENVER (IAAI)", price: 2525 },
  { name: "CO-DENVER EAST (IAAI)", price: 2500 },
  { name: "CO-WESTERN COLORADO (IAAI)", price: 2750 },
  { name: "CT-HARTFORD (IAAI)", price: 2145 },
  { name: "CT-HARTFORD SOUTH (IAAI)", price: 2115 },
  { name: "DE-NEW CASTLE (IAAI)", price: 2125 },
  { name: "FL-WEST PALM BEACH (IAAI)", price: 2225 },
  { name: "FL-CLEARWATER (IAAI)", price: 2025 },
  { name: "FL-FORT MYERS (IAAI)", price: 2250 },
  { name: "FL-FORT PIERCE (IAAI)", price: 2175 },
  { name: "FL-JACKSONVILLE (IAAI)", price: 1985 },
  { name: "FL-MIAMI (IAAI)", price: 1975 },
  { name: "FL-MIAMI NORTH (IAAI)", price: 2060 },
  { name: "FL-ORLANDO (IAAI)", price: 2025 },
  { name: "FL-ORLANDO NORTH (IAAI)", price: 2025 },
  { name: "FL-PENSACOLA (IAAI)", price: 2060 },
  { name: "FL-TAMPA (IAAI)", price: 2125 },
  { name: "FL-TAMPA NORTH (IAAI)", price: 2125 },
  { name: "GA-AUGUSTA (IAAI)", price: 2125 },
  { name: "GA-ATLANTA (IAAI)", price: 2060 },
  { name: "GA-ATLANTA EAST (IAAI)", price: 2150 },
  { name: "GA-ATLANTA NORTH (IAAI)", price: 2150 },
  { name: "GA-ATLANTA SOUTH (IAAI)", price: 2060 },
  { name: "GA-ATLANTA WEST (IAAI)", price: 2200 },
  { name: "GA-LAKE CITY (IAAI)", price: 2060 },
  { name: "GA-MACON (IAAI)", price: 1925 },
  { name: "GA-SAVANNAH (IAAI)", price: 1895 },
  { name: "GA-TIFTON (IAAI)", price: 2000 },
  { name: "HI-HONOLULU (IAAI)", price: 4525 },
  { name: "HI-KAUAI (IAAI)", price: 6375 },
  { name: "IA-DAVENPORT (IAAI)", price: 2350 },
  { name: "IA-DES MOINES (IAAI)", price: 2575 },
  { name: "ID-BOISE (IAAI)", price: 2925 },
  { name: "IL-CHICAGO NORTH (IAAI)", price: 2425 },
  { name: "IL-CHICAGO SOUTH (IAAI)", price: 2425 },
  { name: "IL-CHICAGO WEST (IAAI)", price: 2350 },
  { name: "IL-DREAM RIDES (IAAI)", price: 2425 },
  { name: "IL-LINCOLN (IAAI)", price: 2565 },
  { name: "IL-SPECIALTY DIVISION (IAAI)", price: 2355 },
  { name: "IL-ST.LOUIS (IAAI)", price: 2525 },
  { name: "IN-FORT WAYNE (IAAI)", price: 2460 },
  { name: "IN-INDIANAPOLIS (IAAI)", price: 2425 },
  { name: "IN-SOUTH BEND (IAAI)", price: 2425 },
  { name: "KS-KANSAS CITY (IAAI)", price: 2585 },
  { name: "KS-WICHITA (IAAI)", price: 2325 },
  { name: "KY-ASHLAND (IAAI)", price: 2175 },
  { name: "KY-BOWLING GREEN (IAAI)", price: 2175 },
  { name: "KY-LOUISVILLE (IAAI)", price: 2425 },
  { name: "KY-LOUISVILLE NORTH (IAAI)", price: 2375 },
  { name: "KY-PADUCAH (IAAI)", price: 2225 },
  { name: "LA-BATON ROUGE (IAAI)", price: 2315 },
  { name: "LA-LAFAYETTE (IAAI)", price: 2280 },
  { name: "LA-NEW ORLEANS (IAAI)", price: 2315 },
  { name: "LA-NEW ORLEANS EAST (IAAI)", price: 2195 },
  { name: "LA-SHREVOPORT (IAAI)", price: 2280 },
  { name: "MA-BOSTON SHIRLEY (IAAI)", price: 2180 },
  { name: "MA-TAUNTON (IAAI)", price: 2180 },
  { name: "MA-TEMPLETON (IAAI)", price: 2180 },
  { name: "MD-ELKTON (IAAI)", price: 2175 },
  { name: "MD-BALTIMORE (IAAI)", price: 2145 },
  { name: "MD-DUNDALK (IAAI)", price: 2145 },
  { name: "MD-LAUREL (IAAI)", price: 2145 },
  { name: "MD-METRO DC (IAAI)", price: 2145 },
  { name: "MD-ROSEDALE (IAAI)", price: 2145 },
  { name: "MD-WHITE PLANS AUX LOT (IAAI)", price: 2145 },
  { name: "ME-WINDHAM (IAAI)", price: 2325 },
  { name: "ME-PORTLAND GORHAM (IAAI)", price: 2390 },
  { name: "MI-WAYLAND (IAAI)", price: 2475 },
  { name: "MI-DETROIT (IAAI)", price: 2600 },
  { name: "MI-FLINT (IAAI)", price: 2460 },
  { name: "MI-GRAND RAPIDS (IAAI)", price: 2565 },
  { name: "MI-GREAT LAKES (IAAI)", price: 2465 },
  { name: "MN-IAA FARIBAULT (IAAI)", price: 2600 },
  { name: "MN-MINNEAPOLIS SOUTH (IAAI)", price: 2535 },
  { name: "MN-MINNEAPOLIS/ST.PAUL (IAAI)", price: 2530 },
  { name: "MN-ST. CLOUD (IAAI)", price: 2635 },
  { name: "MO-KANSAS CITY EAST (IAAI)", price: 2275 },
  { name: "MO-SPRINGFIELD (IAAI)", price: 2425 },
  { name: "MS-GRENADA (IAAI)", price: 2175 },
  { name: "MS-GULF COAST (IAAI)", price: 2175 },
  { name: "MS-JACKSON (IAAI)", price: 2055 },
  { name: "MT-BILLINGS (IAAI)", price: 3050 },
  { name: "MT-MISSOULA (IAAI)", price: 3125 },
  { name: "NC-ASHEVILLE (IAAI)", price: 2165 },
  { name: "NC-CHARLOTTE (IAAI)", price: 2215 },
  { name: "NC-CONCORD (IAAI)", price: 2200 },
  { name: "NC-GREENSBORO (IAAI)", price: 2215 },
  { name: "NC-HIGH POINT (IAAI)", price: 2175 },
  { name: "NC-RALEIGH (IAAI)", price: 2165 },
  { name: "NC-WILMINGTON (IAAI)", price: 2060 },
  { name: "ND-FARGO (IAAI)", price: 2925 },
  { name: "NE-OMAHA (IAAI)", price: 2575 },
  { name: "NH-MANCHESTER (IAAI)", price: 2250 },
  { name: "NJ-PORT MURRAY (IAAI)", price: 2045 },
  { name: "NJ-AVANEL NEW JERSEY (IAAI)", price: 1950 },
  { name: "NJ-CENTRAL NEW JERSEY (IAAI)", price: 1945 },
  { name: "NJ-ENGLISHTOWN (IAAI)", price: 1950 },
  { name: "NJ-NORTHERN NEW JERSEY (IAAI)", price: 1915 },
  { name: "NJ-SAYREVILLE (IAAI)", price: 1905 },
  { name: "NJ-SOUTHERN NEW JERSEY (IAAI)", price: 2040 },
  { name: "NJ-SYREVILLE (IAAI)", price: 1955 },
  { name: "NM-ALBUQUERQUE (IAAI)", price: 2425 },
  { name: "NV-LAS VEGAS (IAAI)", price: 2675 },
  { name: "NV-RENO (IAAI)", price: 2800 },
  { name: "NY-ALBANY (IAAI)", price: 2075 },
  { name: "NY-BUFFALO (IAAI)", price: 2320 },
  { name: "NY-LONG ISLAND (IAAI)", price: 2040 },
  { name: "NY-MONTICELLO (IAAI)", price: 2055 },
  { name: "NY-NEWBURGH (IAAI)", price: 2005 },
  { name: "NY-ROCHESTER (IAAI)", price: 2215 },
  { name: "NY-STATEN ISLAND (IAAI)", price: 1905 },
  { name: "NY-SYRACUSE (IAAI)", price: 2275 },
  { name: "OH-AKRON-CANTON (IAAI)", price: 2320 },
  { name: "OH-CINCINNATI (IAAI)", price: 2285 },
  { name: "OH-CINCINNATI SOUTH (IAAI)", price: 2285 },
  { name: "OH-CLEVELAND (IAAI)", price: 2390 },
  { name: "OH-COLUMBUS (IAAI)", price: 2355 },
  { name: "OH-DAYTON (IAAI)", price: 2425 },
  { name: "OK-OKLAHOMA CITY (IAAI)", price: 2300 },
  { name: "OK-TULSA (IAAI)", price: 2375 },
  { name: "OR-EUGENE (IAAI)", price: 3045 },
  { name: "OR-PORTLAND (IAAI)", price: 3285 },
  { name: "OR-PORTLAND WEST (IAAI)", price: 2725 },
  { name: "PA-ALTOONA (IAAI)", price: 2250 },
  { name: "PA-BRIDGEPORT (IAAI)", price: 2005 },
  { name: "PA-ERIE (IAAI)", price: 2390 },
  { name: "PA-PHILADELPHIA (IAAI)", price: 2035 },
  { name: "PA-PITTSBURGH (IAAI)", price: 2355 },
  { name: "PA-PITTSBURGH NORTH (IAAI)", price: 2355 },
  { name: "PA-SCRANTON (IAAI)", price: 2110 },
  { name: "PA-YORK SPRINGS (IAAI)", price: 2040 },
  { name: "RI-PROVIDENCE (IAAI)", price: 2215 },
  { name: "SC-CHARLESTON (IAAI)", price: 1935 },
  { name: "SC-COLUMBIA (IAAI)", price: 1955 },
  { name: "SC-GREENVILLE (IAAI)", price: 1955 },
  { name: "SC-LEXINGTON (IAAI)", price: 1955 },
  { name: "SD-SIOUX FALLS (IAAI)", price: 2575 },
  { name: "TN-CHATTANOOGA (IAAI)", price: 2175 },
  { name: "TN-KNOXVILLE (IAAI)", price: 2235 },
  { name: "TN-MEMPHIS (IAAI)", price: 2165 },
  { name: "TN-NASHVILLE (IAAI)", price: 2165 },
  { name: "TX-ABILENE (IAAI)", price: 2275 },
  { name: "TX-AMARILLO (IAAI)", price: 2325 },
  { name: "TX-AUSTIN (IAAI)", price: 2185 },
  { name: "TX-AUSTIN NORTH (IAAI)", price: 2235 },
  { name: "TX-CORPUS CHRISTI (IAAI)", price: 2185 },
  { name: "TX-DALAS/FT. WORTH (IAAI)", price: 2265 },
  { name: "TX-DALLAS (IAAI)", price: 2185 },
  { name: "TX-EL PASO (IAAI)", price: 2385 },
  { name: "TX-FORT WORTH NORTH (IAAI)", price: 2265 },
  { name: "TX-HOUSTON (IAAI)", price: 2085 },
  { name: "TX-HOUSTON SOUTH (IAAI)", price: 2085 },
  { name: "TX-HOUSTON NORTH (IAAI)", price: 2085 },
  { name: "TX-LONGVIEW (IAAI)", price: 2185 },
  { name: "TX-LUBBOCK (IAAI)", price: 2465 },
  { name: "TX-MCALLEN (IAAI)", price: 2185 },
  { name: "TX-PERMIAN BASIN (IAAI)", price: 2305 },
  { name: "TX-SAN ANTONIO SOUTH (IAAI)", price: 2265 },
  { name: "UT-PROVO (IAAI)", price: 3085 },
  { name: "UT-SALT LAKE CITY (IAAI)", price: 3050 },
  { name: "VA-CULPEPER (IAAI)", price: 2145 },
  { name: "VA-FREDERICKSBURG SOUTH (IAAI)", price: 2145 },
  { name: "VA-NORTHERN VIRGINIA (IAAI)", price: 2145 },
  { name: "VA-PULASKI (IAAI)", price: 2390 },
  { name: "VA-RICHMOND (IAAI)", price: 2215 },
  { name: "VA-ROANOKE (IAAI)", price: 2215 },
  { name: "VA-SUFFOLK (IAAI)", price: 2200 },
  { name: "VA-TIDEWATER (IAAI)", price: 2255 },
  { name: "VT-BURLINGTON (IAAI)", price: 2325 },
  { name: "WA-SEATTLE (IAAI)", price: 3155 },
  { name: "WA-SEATTLE SOUTH (IAAI)", price: 3205 },
  { name: "WA-SPOKANE (IAAI)", price: 3325 },
  { name: "WI-APPLETON (IAAI)", price: 2600 },
  { name: "WI-MILWAUKEE (IAAI)", price: 2495 },
  { name: "WI-PORTAGE (IAAI)", price: 2565 },
  { name: "WV-BUCKHANNON (IAAI)", price: 2375 },
  { name: "WV-SHADY SPRING (IAAI)", price: 2495 },
  { name: "WY-CASPER (IAAI)", price: 3100 },
];
